Add directory soft delete
infratographer/fertilesoil pull request #52
Opened 2023-01-19 15:28 UTC by mikemrm

Implements soft deletions for directories.
Deleting a parent directory also deletes all child directories.

See #9

2023-01-19 17:11 UTC, JAORMX commented
Let's keep high test coverage

2023-01-24 06:38 UTC, JAORMX requested changes
Very nice! Thanks for working on this!

Can you add the openapi specification for the delete call in https://github.com/infratographer/fertilesoil/blob/main/treeman-openapi-v1.yaml ? It's currently marked as a TODO.

Also, now that get/list of directories (and root ones) does not return deleted entries, can you create a GH issue about this? We should allow an admin to list deleted entries with a query parameter or something of the sort (we'd deny this functionality to normal users).

cc @pereztr5 can you review this as well?

2023-01-24 13:03 UTC, mikemrm commented
I've updated the spec, and created #55

2023-01-24 13:07 UTC, JAORMX approved these changes

2023-01-24 13:07 UTC, merged